name: Main

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Build Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o ./journeys.api-linux-amd64 cmd/journeys/journeys.go
          tar -czf journeys.api-linux-amd64.tar.gz ./journeys.api-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ./journeys.api-linux-amd64
            ./journeys.api-linux-amd64.tar.gz
